# Uncomment the following lines to enable the RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the OLED Display
# CONFIG_ZMK_DISPLAY=y

# Enable physical pointing device and mouse emulation
CONFIG_ZMK_POINTING=y

# Refer to erenatas & grassfedreeve & Hlinyi repo

# Increasing the transmit power of the keyboard's BLE radio (+8 dBm)
# 增加键盘的 BLE 无线电的发射功率，用解决延迟和左右通讯不佳的问题
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# ### Bluetooth ###
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
CONFIG_BT_BUF_ACL_TX_COUNT=32
CONFIG_BT_L2CAP_TX_BUF_COUNT=32

# Enables a combination of settings that are planned to be default in future
# versions of ZMK to improve connection stability. This includes changes to
# timing on BLE pairing initiation, restores use of the updated/new LLCP
# implementation, and disables 2M PHY support.
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable fetching split peripheral battery levels to the central side
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# Enable central reporting of split battery levels to hosts
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# 电池电量报告间隔时间单位是秒
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Max num of behaviors to allow queueing from a macro or other complex behavior
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

# # Combo configuration
# CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=10
# CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=10

# # 进入空闲状态前的不活动毫秒数
# CONFIG_ZMK_IDLE_TIMEOUT=15000
# 1800000 毫秒 = 30 分钟 * 60 秒 * 1000
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000

# # 增加键盘消抖
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=15
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=15

# ZMK Studio Support
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n